services:
  - type: web
    name: aula-app
    env: node
    plan: free
    region: ohio  # ou use frankfurt se estiver na Europa
    buildCommand: |
      npm install
      npx prisma generate  # Gera os arquivos do Prisma Client
      npm run build  # Roda o build do TypeScript
    startCommand: |
      npx prisma migrate deploy  # Aplica as migrações do Prisma
      npm run start  # Inicia o app com o server compilado