services:
  - type: web
    name: aula-app
    env: node
    buildCommand: |
      npm install
      npm run build
      npm run prisma:migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SECRET
        value: your-secret-key-here