@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyNzUzMjc5MCwiZXhwIjoxNzI3NTM2MzkwfQ.0-2yJGPTw8LnAnBoahu3QcfkHJHHOQtYRli05G6XbmQ
@host = https://aula-app.onrender.com

### Login
POST {{host}}/auth/login
Content-Type: application/json

{
    "username": "jorge.frasson",
    "password": "123456789"
}

### Register user
POST {{host}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "usuario.teste",
    "email": "example@email.com",
    "password": "123456",
    "name": "Usuário Teste de Exemplo",
    "cpf": "14545220703"
}