@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyNzUzMjc5MCwiZXhwIjoxNzI3NTM2MzkwfQ.0-2yJGPTw8LnAnBoahu3QcfkHJHHOQtYRli05G6XbmQ
@host = https://aula-app.onrender.com
### Get users
GET {{host}}/users/list
Authorization: Bearer {{token}}
### Save user
POST {{host}}/users/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "jorge.frasson1",
    "email": "jorge.frasson148@gmail.com",
    "password": "123456",
    "name": "Jorge Henrique Frasson",
    "cpf": "14545220704"
}

### Update user
PUT {{host}}/users/update/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "jorge.frasson2",
    "email": "jorge.frasson@gmail.com",
    "password": "123456",
    "name": "Jorge Henrique Frasson"
}

### Delete user
DELETE {{host}}/users/delete/4 HTTP/1.1
Authorization: Bearer {{token}}